backend:
  name: github
  repo: dnwk/n7dmr
  branch: master # Branch to update (optional; defaults to master)
local_backend: true
# These lines should *not* be indented
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads